import path from "path";
let config = {};
config.logFileDir = path.join(__dirname, '../../log');
config.logFileName = 'app.log';
config.dbHost = process.env.dbHost || 'localhost';
config.dbPort = process.env.dbPort || '27017';
config.dbName = process.env.dbName || 'blog';
config.serverPort = process.env.serverPort || 8088;
config.secret = 'hahaha';
export default config;
